[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "astro"
scope = "source.astro"
# injection-regex = "astro"
file-types = ["astro"]
# language-server = { command = "astro-ls", args = ["--stdio"], config.typescript.tsdk = "/usr/local/lib/node_modules/typescript/lib" }
language-server = { command = "astro-ls", args = ["--stdio"]}
config = {typescript = {tsdk = "/usr/local/lib/node_modules/typescript/lib"}, environment = "node"}
